### ISSUE TITLE
Is it possible to represent the frequencies of two samples in the same .html browser?

### ISSUE THREAD

**Issue by Coracollar** [wdecoster/methplotlib#21]
Hi, 
I was wondering whether besides the option of representing one pair of methylation frequencies and calls per .html, there was an option to generate a methylation html browser that shows the frequencies of two samples at the same time to compare them.

Thanks

**Comment by wdecoster** [comment]
I'm not sure if I understand what exactly you are hoping to get. Could you take a look at the [examples](https://gigabaseorgigabyte.wordpress.com/2020/02/18/methplotlib-examples/) and see if the plot you want is there?

**Comment by Coracollar** [comment]
Yes! The forth plot.

**Comment by wdecoster** [comment]
You'll get that if you just use two or more frequency files as input, and do not use the --split option.

If you add raw methylation likelihoods together with the frequencies then the tracks will be split automatically. I don't think I have a good way around that at the moment.

**Comment by Coracollar** [comment]
I have tried that but obtained:

(methplot) [coracollar@spartan-login2 CORT13]$ methplotlib -m
/data/cephfs/punim1048/allbarcoded/CORT/CORT13/chr11_cort13_calls_R.tsv \

> /data/cephfs/punim1048/allbarcoded/CORT/CORT13/chr11_cort13_frec_R.tsv \

>
/data/cephfs/punim1048/allbarcoded/Control/C3/chr11_methylation_calls_R.tsv
\

>
/data/cephfs/punim1048/allbarcoded/Control/C3/chr11_methylation_frec_R.tsv \

> -n calls frequencies calls frequencies \

> -w chr11:11,928,499-12,039,420

Traceback (most recent call last):

  File "/home/coracollar/anaconda3/envs/methplot/bin/methplotlib", line 10,
in <module>

    sys.exit(main())

  File
"/home/coracollar/anaconda3/envs/methplot/lib/python3.7/site-packages/methplotlib/methplotlib.py",
line 25, in main

    qc_plots(meth_data, window, qcpath=args.qcfile, outpath=args.outfile)

  File
"/home/coracollar/anaconda3/envs/methplot/lib/python3.7/site-packages/methplotlib/methplotlib.py",
line 177, in qc_plots

    full = data[0].join(data[1:]).dropna(how="any", axis="index")

  File
"/home/coracollar/.local/lib/python3.7/site-packages/pandas/core/frame.py",
line 7209, in join

    other, on=on, how=how, lsuffix=lsuffix, rsuffix=rsuffix, sort=sort

  File
"/home/coracollar/.local/lib/python3.7/site-packages/pandas/core/frame.py",
line 7248, in _join_compat

    frames, axis=1, join="outer", verify_integrity=True, sort=sort

  File
"/home/coracollar/.local/lib/python3.7/site-packages/pandas/core/reshape/concat.py",
line 281, in concat

    sort=sort,

  File
"/home/coracollar/.local/lib/python3.7/site-packages/pandas/core/reshape/concat.py",
line 452, in __init__

    self.new_axes = self._get_new_axes()

  File
"/home/coracollar/.local/lib/python3.7/site-packages/pandas/core/reshape/concat.py",
line 517, in _get_new_axes

    for i in range(ndim)

  File
"/home/coracollar/.local/lib/python3.7/site-packages/pandas/core/reshape/concat.py",
line 517, in <listcomp>

    for i in range(ndim)

  File
"/home/coracollar/.local/lib/python3.7/site-packages/pandas/core/reshape/concat.py",
line 572, in _get_concat_axis

    self._maybe_check_integrity(concat_axis)

  File
"/home/coracollar/.local/lib/python3.7/site-packages/pandas/core/reshape/concat.py",
line 582, in _maybe_check_integrity

    "{overlap!s}".format(overlap=overlap)

ValueError: Indexes have overlapping values: Index(['frequencies'],
dtype='object')

**Comment by wdecoster** [comment]
The cause here is that you reuse the same name for the datasets.  It would be prevented if you would use e.g. frequencies1 and frequencies2:

```
methplotlib -m /data/cephfs/punim1048/allbarcoded/CORT/CORT13/chr11_cort13_calls_R.tsv \
 /data/cephfs/punim1048/allbarcoded/CORT/CORT13/chr11_cort13_frec_R.tsv \
/data/cephfs/punim1048/allbarcoded/Control/C3/chr11_methylation_calls_R.tsv \
/data/cephfs/punim1048/allbarcoded/Control/C3/chr11_methylation_frec_R.tsv \
 -n calls frequencies1 calls frequencies2 \
 -w chr11:11,928,499-12,039,420
```

And that's also not what I told you to do if you want a plot with overlapping frequency tracks. You should then do the following command with just frequencies:

```
methplotlib -m /data/cephfs/punim1048/allbarcoded/CORT/CORT13/chr11_cort13_frec_R.tsv \
/data/cephfs/punim1048/allbarcoded/Control/C3/chr11_methylation_frec_R.tsv \
 -n calls frequencies1 calls frequencies2 \
 -w chr11:11,928,499-12,039,420
```

As I said: 
> If you add raw methylation likelihoods together with the frequencies then the tracks will be split automatically. I don't think I have a good way around that at the moment.

If you include CALL files you won't get overlapping frequencies. That's just how the code is implemented at the moment.
