### ISSUE TITLE
Color modification frequency

### ISSUE THREAD

**Issue by JesseBNL** [wdecoster/methplotlib#28]
Hi,

Very nice tool for the methylation visualization. But I cannot find what the color of the line that indicates the modification frequency represents. As the line is one consistent color, even when it goes up or down, it seems not to correlate with the likelihood. The lines have different colors (blue, orange, dark red) in different plots. 

Thank you.

**Comment by wdecoster** [comment]
The color doesn't mean anything - each sample will just get a color. To see likelihoods you need to use the per-read per-position calls from nanopolish, and not the file you got from calculate_methylation_frequency.py. In the frequency file there is no information about likelihood anymore, I believe.
