### ISSUE TITLE
Unable to install using pip

### ISSUE THREAD

**Issue by dipannita-g** [wdecoster/methplotlib#30]
Hi there!

I tried to install methplotlib using pip (pip install methplotlib)  but it says:

```
Could not find a version that satisfies the requirement methplotlib (from versions: )
No matching distribution found for methplotlib
```
I am not sure how to install it otherwise. Any suggestion will be appreciated. Thank you!

**Comment by wdecoster** [comment]
Which python version do you have installed?

**Comment by dipannita-g** [comment]
It is Python 3.7.5

**Comment by wdecoster** [comment]
Can you please try `python -m pip install methplotlib` and see if that helps?

**Comment by dipannita-g** [comment]
`python -m pip install methplotlib` is giving the same error:

```
$ python -m pip install methplotlib
Collecting methplotlib
  Could not find a version that satisfies the requirement methplotlib (from versions: )
No matching distribution found for methplotlib
```

**Comment by endrebak** [comment]
Would using conda with `conda install -c bioconda methplotlib` work for you?

**Comment by dipannita-g** [comment]
I was able to install it using pip. My default python was set to Python 2 instead of 3. Changing that and installing python3.7-dev solved the issue. 

Thanks a bunch for your time and recommendations!
