### ISSUE TITLE
gtf fails

### ISSUE THREAD

**Issue by JWDebler** [wdecoster/methplotlib#32]
I am trying to run methplotlib with nanopolish results and a genome and gtf file like this:

`methplotlib -m AlKewell.nanopolish.methylation_frequency.tsv -n AlKewell -w AlKewell_ctg_3:1-2245191 -g test.gtf`

I extracted a tiny bit from the gtf file that sits within the window I gave to methplotlib:

```
AlKewell_ctg_3	GeneMark.hmm	exon	1910059	1910105	0	+	.	gene_id "278_g"; transcript_id "278_t";
AlKewell_ctg_3	GeneMark.hmm	start_codon	1910059	1910061	.	+	0	gene_id "278_g"; transcript_id "278_t"; count "1_1";
AlKewell_ctg_3	GeneMark.hmm	CDS	1910059	1910105	.	+	0	gene_id "278_g"; transcript_id "278_t"; cds_type "Initial"; count "1_2";
```

This is the error I get:

```
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/bin/methplotlib", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/methplotlib/methplotlib.py", line 35, in main
    binary=args.binary,   
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/methplotlib/methplotlib.py", line 106, in meth_browser
    annotation_traces, y_max = plots.gtf_annotation(gtf, window, simplify)  
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/methplotlib/plots.py", line 35, in gtf_annotation
    annotation = parse_annotation(gtf, window, simplify) 
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/methplotlib/annotation.py", line 117, in parse_annotation
    gene=tr["gene"].tolist()[0],  
IndexError: list index out of range
```

If I use an extract from the gtf that is not within the window I get this:

```
AlKewell_ctg_16	GeneMark.hmm	exon	1340573	1340784	0	-	.	gene_id "1_g"; transcript_id "1_t";
AlKewell_ctg_16	GeneMark.hmm	stop_codon	1340573	1340575	.	-	0	gene_id "1_g"; transcript_id "1_t"; count "1_1";
AlKewell_ctg_16	GeneMark.hmm	CDS	1340573	1340784	.	-	2	gene_id "1_g"; transcript_id "1_t"; cds_type "Terminal"; count "2_2";
```
`Found 0 transcript(s) in the region.`

Is there something wrong with this gtf? It is straight out of genemark.

Cheers

**Comment by endrebak** [comment]
Do you have a link to the gtf?

**Comment by wdecoster** [comment]
Hmm, I've seen this one before, could you test if you still have the error if you use `--simplify`, to show the annotation as genes rather than transcripts?

**Comment by JWDebler** [comment]
Yes, using `--simplify` doesn't throw that error.

**Comment by JWDebler** [comment]
@endrebak here is a copy of the gtf
[gtf file](https://drive.google.com/file/d/1HTlPHQWe5maHcpHoYdTyUJdn5BcFNvRN/view?usp=sharing)

@wdecoster genemark doesn't include a `gene` field in its gtf, but I have manually added one for a gene I am interested in, and I still get the `Found 0 gene(s) in the region.` notification even when restricting the window to a few 1000 bp up and downstream of the gene's location.

**Comment by wdecoster** [comment]
The code is looking for a `gene_name` in the attributes (last column) of the gtf... The code is a bit buggy, I'm afraid. You have so many flavors of GTF/GFF files...
I guess we can take 'gene_id` in this case?

**Comment by JWDebler** [comment]
I replaced all the 'gene_id' with 'gene_name' and now the script works in `--simplify` mode :-)

**Comment by wdecoster** [comment]
Thanks for the confirmation, but this is something that we will need a more robust fix for :-)

**Comment by JWDebler** [comment]
That would be great. Maybe add GFF support at the same time to save me the conversion of other GFFs to GTF :-)

**Comment by wdecoster** [comment]
Well, GFF should already be supported. That is, to the same extent that GTF is supported ;-)
