### ISSUE TITLE
Window parameter cannot deal with complicated fasta headers

### ISSUE THREAD

**Issue by bastian-wur** [wdecoster/methplotlib#42]
Hi everyone,

I'm trying to use methplotlib, and I've run into some issues.
I'm trying to use it to analyze some reads I called earlier.
Issue number #1) There is no reference for this. To get around this, I converted one of the read fastq files to fasta, and used this one as reference
Issue #2) Obviously the reads don't have nice names. If I use` -w "37b7bed0-436a-4676-a61a-023255f80bee runid=0fa505d79c6c1b4fe0085a62e508181b26c78340 sampleid=I22-1145-01 read=168 ch=445 start_time=2022-05-19T13:59:55Z model_version_id=dna_r10.4.1_e8.2_400bps_hac@v3.5.2:1-200"`
```
I get ERROR: Window (-w/--window) inproperly formatted, examples of accepted formats are:
'chr5:150200605-150423790' or 'ENST00000647408'
```
I do understand the error, but in theory my input is proper, I guess. Just the fasta header is complicated.,

If you have any other advice how I could visualize my data, then I'd be very happy.

Thanks,
Bastian

**Comment by wdecoster** [comment]
Hi Bastian,

I assume you then aligned your data to that one fastq you used as pseudo-reference?
I think not the entire fasta identifier will be used in the sam/bam/cram file - and it might look like `37b7bed0-436a-4676-a61a-023255f80bee` without the rest of the information.

Wouter

**Comment by wdecoster** [comment]
I assume guppy created a BAM file with unaliged reads, i.e. ubam?

**Comment by bastian-wur** [comment]
Sorry, I'm getting back to this so late. Yes, I had run Guppy without a reference at that time. In the meantime I've run it again with a human reference, I've not tested methplotlib yet, but I do not expect any issues with that :).
