### ISSUE TITLE
mehplotlib having trouble finding sklearn

### ISSUE THREAD

**Issue by clock-matt** [wdecoster/methplotlib#44]
So this issue may be entirely on my end, or may be that methplotlib doesn't play well with mamba, but it's having issues finding my sklearn module. Here are the commands I used to install:

mamba create -n methplotlib pip
conda activate methplotlib
pip install methplotlib

but when I try to use it:

methplotlib -h
Traceback (most recent call last):
  File "/home/matthew/anaconda3/envs/methplotlib/bin/methplotlib", line 5, in <module>
    from methplotlib.methplotlib import main
  File "/home/matthew/anaconda3/envs/methplotlib/lib/python3.10/site-packages/methplotlib/methplotlib.py", line 1, in <module>
    import methplotlib.plots as plots
  File "/home/matthew/anaconda3/envs/methplotlib/lib/python3.10/site-packages/methplotlib/plots.py", line 4, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn' 

I checked to make sure sklearn was installed: 
pip install sklearn 
Requirement already satisfied: sklearn in /home/matthew/anaconda3/envs/methplotlib/lib/python3.10/site-packages (0.0.post1)

Thoughts?

**Comment by clock-matt** [comment]
No reason, I just missed the part where it was on conda, so I assumed it was only on pip. I re-installed with conda and everything is working fine now. Thank you.

**Comment by wdecoster** [comment]
> No reason, I just missed the part where it was on conda, so I assumed it was only on pip. I re-installed with conda and everything is working fine now. Thank you.

Oh no worries, I just clarified in the README that you can also use conda :)
