### ISSUE TITLE
sklearn deprecated

### ISSUE THREAD

**Issue by sbecuwe** [wdecoster/methplotlib#46]
Hello

Trying to install methplotlib using pip, I got following error:
```
    The 'sklearn' PyPI package is deprecated, use 'scikit-learn'
    rather than 'sklearn' for pip commands.
```
See also https://pypi.org/project/sklearn/ (which mentions a workaround)

Kind regards
Stefan

**Comment by wdecoster** [comment]
Okay I will change it in the setup.py, for now you can install from conda
