### ISSUE TITLE
sbatch example of methplotlib

### ISSUE THREAD

**Issue by TaniaChP79** [wdecoster/methplotlib#48]
Hello,

I will like to run methplotlib on a cluster and I was wonder if you have an example of a sbatch script to run of the cluster.
As I did not installed the software I am wondering which modules I need to load in order to run the script provided here.
Best,

Tania

**Comment by wdecoster** [comment]
Hi Tania,

No, I don't have an example for that, and the modules may depend on your local setup. You can find the required modules in the setup.py: https://github.com/wdecoster/methplotlib/blob/master/setup.py#L38

Wouter

**Comment by TaniaChP79** [comment]
Okay thanks so much for your reply
