### ISSUE TITLE
Errors supporting bedgraph files

### ISSUE THREAD

**Issue by Ge0rges** [wdecoster/methplotlib#50]
Using version 0.20.1 there are a few errors recognizing the bed graph format as output by Nanopore's mod kit tool.

`utils.py` checks for `4` columns but this file has `5`.

Moreover, it seems like even when that is fixed the tool fails to find records for regions present. For example, running: `methplotlib -m m_positive1.bedgraph m_positive2.bedgraph m_positive3.bedgraph -n freq1 freq2 freq3 -f 106_sub.fna -w contig_13235` with the following gives:

`No records for methylation/barcode01/106_sub-bedgraph/m_positive.bedgraph in contig_13235!`

Despite `m_positive1.bedgraph` being, and the config also being present at least once in the other two bed graph files:

```
contig_13235	74	75	0	1
contig_13235	116	117	0	1
contig_13235	122	123	0	1
contig_13235	135	136	1	1
contig_13235	4865	4866	0	1
contig_13235	4872	4873	0	1
contig_13235	4875	4876	0	1
contig_13235	4880	4881	0	1
contig_13235	4885	4886	0	1
contig_13235	4894	4895	0	1
```

and `cat 106_sub.fna | grep contig_13235` returns `>contig_13235`. This is true for other configs as well. 

I would try this with the latest version however it is not published to Conda or pip, and the local uninstall proved to be a headache.

**Comment by wdecoster** [comment]
How did you fix the issue with the number of columns? I do not think that a file with 5 tab separated fields is a valid bedgraph. See also https://genome.ucsc.edu/goldenPath/help/bedgraph.html

**Comment by Ge0rges** [comment]
I did not fix this issue, but found that the bedgraph file does work with other software such as IGV. I guess this is odd if it doesn't correspond to the standard... Perhaps worth opening an issue with the modkit team.

**Comment by wdecoster** [comment]
methplotlib now also supports bedmethyl format (if running modkit with `--only-tabs`, see also https://github.com/nanoporetech/modkit/issues/43). Those changes still need to be released but will be available later today.

I must say that the variety of formats and standards is getting rather cumbersome to support, but I will still try :)

**Comment by Ge0rges** [comment]
Great! Thanks! I think if it support modkit bedmethyl then there's no need to support bedgraph necessarily. At least with respect to modkit support.
